apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp  # selector for pods.
  replicas: 1
  template:
    metadata: # template for pod.
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webfrontend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__MusicStoreEntities
          value: "Server=musicstore-database;Initial Catalog=MusicStore;User Id=sa;Password=P@ssword1"
        - name: ConnectionStrings__IdentityConnection
          value: "Server=musicstore-database;Initial Catalog=identity;User Id=sa;Password=P@ssword1"
---
apiVersion: v1
kind: Service
metadata:
  name: musicstore-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
  
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 30080

  type: NodePort